# Generated by Django 5.0.14 on 2026-06-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
            ],
            options={
                'verbose_name': 'عضو خبرنامه',
                'verbose_name_plural': 'اعضای خبرنامه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ArioSport', max_length=100, verbose_name='نام سایت')),
                ('tagline', models.CharField(blank=True, default='مرجع حرفه\u200cای اخبار و تحلیل\u200cهای ورزشی', max_length=200, verbose_name='شعار')),
                ('about_short', models.TextField(blank=True, default='مرجع حرفه\u200cای اخبار، تحلیل و مقالات ورزشی. ما با اشتیاق، دنیای ورزش را برای شما روایت می\u200cکنیم.', verbose_name='درباره کوتاه (فوتر)')),
                ('about_full', models.TextField(blank=True, verbose_name='متن کامل صفحه درباره ما')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='لوگو')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='فاوآیکون')),
                ('email', models.EmailField(blank=True, default='info@ariosport.local', max_length=254, verbose_name='ایمیل تماس')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='تلفن')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='آدرس')),
                ('instagram', models.URLField(blank=True, verbose_name='اینستاگرام')),
                ('telegram', models.URLField(blank=True, verbose_name='تلگرام')),
                ('twitter', models.URLField(blank=True, verbose_name='توییتر')),
                ('youtube', models.URLField(blank=True, verbose_name='یوتیوب')),
                ('footer_text', models.CharField(blank=True, default='ArioSport — تمامی حقوق محفوظ است.', max_length=200, verbose_name='متن کپی\u200cرایت فوتر')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
