from django.test import TestCase
from .models import Category


class CategoryModelTest(TestCase):
    def test_slug_autogenerated(self):
        c = Category.objects.create(name="فوتبال")
        self.assertTrue(c.slug)
