# Generated by Django 4.2.28 on 2026-06-23 12:53

import Core_Module.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts_Module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[Core_Module.utils.validate_image_extension, Core_Module.utils.validate_image_size], verbose_name='تصویر پروفایل'),
        ),
    ]
