# Generated by Django 4.2.28 on 2026-06-23 12:53

import Core_Module.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Module', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/', validators=[Core_Module.utils.validate_image_extension, Core_Module.utils.validate_image_size], verbose_name='تصویر شاخص'),
        ),
    ]
